version: "3"
services:

  otel-collector:
    image: otel/opentelemetry-collector:0.76.1
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.7
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.5.1
    restart: always
    ports:
      - "3000:3000"

  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:3.0.0
    restart: always
    command: ["bin/pulsar", "standalone"]
