scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'pulsar-broker'
    scrape_interval: 10s
    static_configs:
      - targets: ['pulsar:8080']
